import type { Metadata } from "next";

import "./globals.css";
import ProviderApp from "@/providers/ProviderApp";

export const metadata: Metadata = {
  title: "Genesiz | Ghost City",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProviderApp>{children}</ProviderApp>
      </body>
    </html>
  );
}
